name: shuttler
description: A shuttle tracking app.
version: 0.1.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  cloud_firestore: ^0.12.9+5
  firebase_dynamic_links: ^0.5.0+1
  google_maps_flutter: ^0.5.21+7
  shared_preferences: ^0.5.3+4
  flutter_platform_widgets: ^0.20.2
  provider: ^3.1.0
  flutter_background_location: ^0.0.4
  location_permissions: ^2.0.3
  location: ^2.3.5
  url_launcher: ^5.2.2
  intl: ^0.16.0
  rect_getter: ^0.0.1
  video_player: ^0.10.2+5
  regexed_validator: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

# To generate logos, run
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/logos/shuttler_logo_android.png"
  image_path_ios: "assets/logos/shuttler_logo_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
    - assets/animations/no-notification.mp4
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
